# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

ai_context_version: 1.1

project:
  name: semantah
  summary: Semantic ingest/index & retrieval services.
  role: knowledge_index_retrieval
  primary_language: python
  visibility: internal

heimgewebe:
  axis:
    - Semantik
  fleet:
    enabled: true
  wgx:
    profile_expected: true
    guard_smoke_expected: true

interfaces:
  consumes:
    - "document_exports"
    - "knowledge_graph_schemas"
  produces:
    - "search APIs"
    - "embeddings"

contracts:
  schemas:
    - path: "contracts/*.schema.json"
      note: "Use local contracts for insights and semantics."

dependencies:
  internal:
    - name: metarepo
      relationship: uses
      interface:
        - knowledge_exports
    - name: contracts
      relationship: uses
      interface:
        - knowledge_graph_schemas
    - name: vault-gewebe
      relationship: uses
      interface:
        - document_exports
        - embeddings_source
  external:
    - name: fastapi
    - name: uvicorn
    - name: faiss

architecture:
  entrypoints:
    - src/main.py
  key_paths:
    - path: src/ingest/
      purpose: document/code ingest
    - path: src/search/
      purpose: semantic search APIs
  data_flow:
    input: docs/code exports
    processing: chunk → embed → index
    output: search APIs

boundaries:
  not_responsible_for:
    - "Raw network ingest (see aussensensor)"
  dangerous_assumptions:
    - "Assume model download is instant"

conventions:
  branching: "main, feature/*"
  commit_prefix: "semantah"
  ci_platform: github_actions

documentation:
  adr: docs/adr/
  runbook: docs/runbook.md

ai_guidance:
  do:
    - store embeddings deterministically for reproducible tests
    - "Start with entrypoints and key_paths."
  dont:
    - mix model versions within the same index without tagging
    - "Invent missing schemas."
